# Generated by Django 4.1.7 on 2023-03-23 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=30)),
                ('pekerjaan', models.CharField(max_length=30)),
                ('foto', models.ImageField(upload_to='foto')),
                ('tentang', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=30)),
                ('keterangan', models.TextField()),
                ('tanggal', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=30)),
                ('foto', models.ImageField(upload_to='foto')),
                ('keterangan', models.TextField()),
                ('tanggal', models.DateTimeField()),
            ],
        ),
    ]
