# Generated by Django 4.1.7 on 2023-03-24 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_rename_project_projects'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='keterangan',
            new_name='pesan',
        ),
    ]
