# Generated by Django 4.1.7 on 2023-03-28 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_rename_keterangan_contact_pesan'),
    ]

    operations = [
        migrations.DeleteModel(
            name='About',
        ),
        migrations.DeleteModel(
            name='Projects',
        ),
    ]
