# Generated by Django 4.1.7 on 2023-03-29 02:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_header'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Header',
            new_name='Kop',
        ),
    ]
