# Generated by Django 4.1.7 on 2023-03-29 03:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_rename_header_kop'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Kop',
        ),
    ]
