# Generated by Django 4.1.7 on 2023-03-31 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_delete_kop'),
    ]

    operations = [
        migrations.CreateModel(
            name='order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=30)),
                ('alamat', models.CharField(max_length=100)),
                ('nohp', models.CharField(max_length=30)),
                ('pesanan', models.CharField(max_length=50)),
            ],
        ),
    ]
